input_image: "test_imgs/mri_brain.jpg"
model_config: "./models/cldm_v15.yaml"
model_weights: "./models/control_sd15_canny.pth"
prompt: "mri brain scan"
low_threshold: 50
high_threshold: 100
num_samples: 1
image_resolution: 512
strength: 1.0
guess_mode: false
ddim_steps: 10
scale: 9.0
seed: 1
eta: 0.0
a_prompt: "good quality"
n_prompt: "animal, drawing, painting, vivid colors, longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality"
save_memory: false